ALTER TABLE decode_field_quality
ADD COLUMN manually_corrected TINYINT(1) NOT NULL DEFAULT 0 AFTER normalized_match,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;